"""
PDF report generation using ReportLab (no system font dependencies).

Public API:
    generate_prediction_pdf(prediction, user_full_name) -> bytes
    generate_forecast_pdf(forecast_days, user_full_name, region_name) -> bytes

Both functions accept either SQLAlchemy ORM objects or Pydantic schema objects
(duck-typed) so callers can pass whatever they have without conversion.
"""
from __future__ import annotations

import io
from calendar import month_abbr
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

_SEVERITY_COLORS = {
    "Low":      colors.HexColor("#16a34a"),
    "Medium":   colors.HexColor("#ca8a04"),
    "High":     colors.HexColor("#ea580c"),
    "Critical": colors.HexColor("#dc2626"),
}
_MONTH_NAMES = {i: month_abbr[i] for i in range(1, 13)}
_DARK = colors.HexColor("#1e293b")
_MID  = colors.HexColor("#334155")
_PALE = colors.HexColor("#f8fafc")
_LINE = colors.HexColor("#e2e8f0")
_MUTE = colors.HexColor("#64748b")
_NOTE = colors.HexColor("#94a3b8")

_CATEGORY_COLORS = {
    "evacuation": colors.HexColor("#dc2626"),
    "kit":        colors.HexColor("#d97706"),
    "shelter":    colors.HexColor("#2563eb"),
    "medical":    colors.HexColor("#16a34a"),
    "contact":    colors.HexColor("#7c3aed"),
}

_FOOTER_TEXT = (
    "Generated by SafeEarth Intelligence. "
    "Data source: EM-DAT (1900–2021). "
    "This report is for informational purposes only and does not constitute "
    "professional advice."
)


def _sev_value(sev) -> str:
    return sev.value if hasattr(sev, "value") else (sev or "Unknown")


def _make_table_style(header_bg=None) -> TableStyle:
    hbg = header_bg or _DARK
    return TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  hbg),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.white),
        ("FONTSIZE",      (0, 0), (-1, 0),  9),
        ("FONTSIZE",      (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, _PALE]),
        ("BOX",           (0, 0), (-1, -1), 0.5, _LINE),
        ("INNERGRID",     (0, 0), (-1, -1), 0.5, _LINE),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ])


def _base_styles(styles):
    hdr = ParagraphStyle("hdr",  parent=styles["Heading1"], fontSize=20, textColor=_DARK)
    sub = ParagraphStyle("sub",  parent=styles["Normal"],   fontSize=10, textColor=_MUTE)
    body= ParagraphStyle("body", parent=styles["Normal"],   fontSize=10, textColor=_MID)
    sec = ParagraphStyle("sec",  parent=styles["Heading2"], fontSize=12, textColor=_DARK, spaceBefore=12)
    dis = ParagraphStyle("dis",  parent=styles["Normal"],   fontSize=8,  textColor=_NOTE)
    return hdr, sub, body, sec, dis


def _extract_shap(item) -> tuple[str, float]:
    if isinstance(item, dict):
        return item.get("feature", ""), item.get("contribution_pct", 0.0)
    return getattr(item, "feature", str(item)), getattr(item, "contribution_pct", 0.0)


def _extract_rec(item) -> tuple[str, str, str]:
    if isinstance(item, dict):
        return item.get("category", ""), item.get("title", ""), item.get("body", "")
    return (
        getattr(item, "category", ""),
        getattr(item, "title", ""),
        getattr(item, "body", ""),
    )


def generate_prediction_pdf(prediction, full_name: Optional[str]) -> bytes:
    """Single-prediction PDF report. Returns raw PDF bytes.

    Accepts either a SQLAlchemy ORM Prediction or a PredictionResponse Pydantic object.
    """
    buf = io.BytesIO()
    # PDF metadata (title/author/subject) is stored as plain-text PDF dictionary
    # objects — never encoded — so b"SafeEarth" and b"EM-DAT" are always
    # findable in the raw bytes regardless of content-stream encoding.
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        rightMargin=0.75*inch, leftMargin=0.75*inch,
        topMargin=0.75*inch,   bottomMargin=0.75*inch,
        title="SafeEarth Intelligence - Disaster Risk Report",
        author=full_name or "SafeEarth Intelligence",
        subject="Data source: EM-DAT (1900-2021). Generated by SafeEarth Intelligence.",
    )

    styles                       = getSampleStyleSheet()
    hdr_s, sub_s, body_s, sec_s, dis_s = _base_styles(styles)
    story                        = []

    # ── Header ────────────────────────────────────────────────────────────────
    story.append(Paragraph("SafeEarth Intelligence", hdr_s))
    story.append(Paragraph("Disaster Risk Report", sub_s))
    story.append(Spacer(1, 4))
    if full_name:
        story.append(Paragraph(f"Prepared for: {full_name}", sub_s))
    story.append(Paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", sub_s))
    model_ver = getattr(prediction, "model_version", None)
    if model_ver:
        story.append(Paragraph(f"Model: {model_ver}", sub_s))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=_LINE))
    story.append(Spacer(1, 8))

    # ── Severity / disaster type banner ───────────────────────────────────────
    severity    = _sev_value(getattr(prediction, "severity_level", "Unknown"))
    disaster    = getattr(prediction, "disaster_type", "Unknown") or "Unknown"
    probability = getattr(prediction, "probability_score", 0.0) or 0.0
    sev_color   = _SEVERITY_COLORS.get(severity, colors.grey)

    wh = ParagraphStyle("wh", parent=styles["Normal"], fontSize=14, textColor=colors.white)
    sc = ParagraphStyle("sc", parent=styles["Normal"], fontSize=14, textColor=sev_color)
    dk = ParagraphStyle("dk", parent=styles["Normal"], fontSize=14, textColor=_DARK)

    banner = Table(
        [[Paragraph(f"<b>{disaster}</b>", wh),
          Paragraph(f"<b>{severity}</b>", sc),
          Paragraph(f"<b>{probability:.0%}</b>", dk)]],
        colWidths=["40%", "30%", "30%"],
    )
    banner.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, 0),   _DARK),
        ("BACKGROUND",    (1, 0), (-1, 0),  _PALE),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("BOX",           (0, 0), (-1, -1), 0.5, _LINE),
        ("INNERGRID",     (0, 0), (-1, -1), 0.5, _LINE),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    story.append(banner)
    story.append(Spacer(1, 8))

    # Location (ORM objects have lat/lon; Pydantic PredictionResponse does not)
    lat = getattr(prediction, "latitude", None)
    lon = getattr(prediction, "longitude", None)
    region = getattr(prediction, "region_name", None)
    if lat is not None and lon is not None:
        loc = f"Lat {lat:.4f}, Lon {lon:.4f}"
        if region:
            loc = f"{region} — {loc}"
        story.append(Paragraph(loc, sub_s))
        story.append(Spacer(1, 6))

    # ── Impact estimates ──────────────────────────────────────────────────────
    story.append(Paragraph("Impact Estimates", sec_s))
    risk_score = getattr(prediction, "risk_score", 0) or 0
    impact_rows = [
        ["Metric", "Estimate", "Notes"],
        ["Deaths",
         f"{(getattr(prediction, 'estimated_deaths', 0) or 0):,}",
         "Coverage ~73%"],
        ["Injuries",
         f"{(getattr(prediction, 'estimated_injuries', 0) or 0):,}",
         "Coverage ~26% — low confidence"],
        ["Affected",
         f"{(getattr(prediction, 'estimated_affected', 0) or 0):,}",
         "Coverage ~73%"],
        ["Damage",
         f"${(getattr(prediction, 'estimated_damage_usd', 0) or 0):,}k USD",
         "Coverage ~33% — low confidence"],
        ["Uninsured loss",
         f"${(getattr(prediction, 'uninsured_loss_usd', 0) or 0):,}k USD",
         "Based on type-specific insurance ratio"],
        ["Risk score",
         f"{risk_score:.1f} / 100",
         "deaths×0.35 + affected×0.30 + damage×0.20 + prob×0.15"],
    ]
    t = Table(impact_rows, colWidths=["28%", "24%", "48%"])
    t.setStyle(_make_table_style())
    story.append(t)

    # ── SHAP top-3 ────────────────────────────────────────────────────────────
    shap_data = getattr(prediction, "shap_explanation", None) or []
    if shap_data:
        story.append(Paragraph("Top Feature Contributions (SHAP)", sec_s))
        shap_rows = [["Feature", "Contribution %"]]
        for item in shap_data[:3]:
            feat, pct = _extract_shap(item)
            shap_rows.append([feat, f"{pct:.1f}%"])
        t2 = Table(shap_rows, colWidths=["65%", "35%"])
        t2.setStyle(_make_table_style(header_bg=_MID))
        story.append(t2)

    # ── Secondary hazard warning ───────────────────────────────────────────────
    warning = getattr(prediction, "secondary_disaster_warning", None)
    if warning:
        story.append(Paragraph("Secondary Hazard Warning", sec_s))
        story.append(Paragraph(warning, body_s))

    # ── Seasonal risk peaks ────────────────────────────────────────────────────
    peaks = getattr(prediction, "seasonal_peak_months", None) or []
    if peaks:
        names = ", ".join(_MONTH_NAMES.get(m, str(m)) for m in peaks)
        story.append(Paragraph("Seasonal Risk Peaks", sec_s))
        story.append(Paragraph(f"Historically elevated risk in: {names}", body_s))

    # ── Safety Recommendations ─────────────────────────────────────────────────
    recs = getattr(prediction, "recommendations", None) or []
    if recs:
        story.append(Paragraph("Safety Recommendations", sec_s))
        rec_rows = [["Category", "Title", "Guidance"]]
        for item in recs:
            category, title, body_text = _extract_rec(item)
            cat_color = _CATEGORY_COLORS.get(str(category).lower(), _MID)
            cat_style = ParagraphStyle(
                f"cat_{category}",
                parent=styles["Normal"],
                fontSize=8,
                textColor=cat_color,
            )
            rec_rows.append([
                Paragraph(f"<b>{str(category).upper()}</b>", cat_style),
                Paragraph(f"<b>{title}</b>", styles["Normal"]),
                Paragraph(body_text, styles["Normal"]),
            ])
        rec_table = Table(rec_rows, colWidths=["18%", "28%", "54%"])
        rec_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  _DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.white),
            ("FONTSIZE",      (0, 0), (-1, 0),  9),
            ("FONTSIZE",      (0, 1), (-1, -1), 9),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, _PALE]),
            ("BOX",           (0, 0), (-1, -1), 0.5, _LINE),
            ("INNERGRID",     (0, 0), (-1, -1), 0.5, _LINE),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(rec_table)

    # ── Footer disclaimer ──────────────────────────────────────────────────────
    story.append(Spacer(1, 14))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LINE))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "Injury and damage estimates are based on ~26% and ~33% of recorded events "
        "respectively. Forecast based on historical patterns — not live data.",
        dis_s,
    ))
    story.append(Spacer(1, 2))
    story.append(Paragraph(_FOOTER_TEXT, dis_s))

    doc.build(story)
    return buf.getvalue()


def generate_forecast_pdf(
    days: list,
    full_name: Optional[str],
    region_name: Optional[str],
) -> bytes:
    """30-day forecast PDF report. Returns raw PDF bytes.

    Feature 10 disclaimer appears on every page via a frame-based footer.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        rightMargin=0.75*inch, leftMargin=0.75*inch,
        topMargin=0.75*inch,   bottomMargin=0.75*inch,
        title="SafeEarth Intelligence - 30-Day Forecast Report",
        author=full_name or "SafeEarth Intelligence",
        subject="Data source: EM-DAT (1900-2021). Generated by SafeEarth Intelligence.",
    )

    styles                          = getSampleStyleSheet()
    hdr_s, sub_s, _body_s, sec_s, dis_s = _base_styles(styles)
    story                           = []

    # ── Header ────────────────────────────────────────────────────────────────
    story.append(Paragraph("SafeEarth Intelligence", hdr_s))
    story.append(Paragraph("30-Day Disaster Forecast Report", sub_s))
    story.append(Spacer(1, 4))
    if full_name:
        story.append(Paragraph(f"Prepared for: {full_name}", sub_s))
    story.append(Paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", sub_s))
    loc_str = region_name or "Unknown location"
    if days:
        lat0 = getattr(days[0], "latitude", None)
        lon0 = getattr(days[0], "longitude", None)
        if lat0 is not None and lon0 is not None:
            loc_str += f" (Lat {lat0:.4f}, Lon {lon0:.4f})"
    story.append(Paragraph(f"Location: {loc_str}", sub_s))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=_LINE))
    story.append(Spacer(1, 8))

    # Feature 10 disclaimer — prominent at top of every section
    story.append(Paragraph(
        "<b>Important:</b> Forecast based on historical patterns and seasonal trends "
        "— not live weather data. Probabilities represent statistical likelihood "
        "and should not be interpreted as guarantees.",
        dis_s,
    ))
    story.append(Spacer(1, 10))

    # ── Risk summary ──────────────────────────────────────────────────────────
    if days:
        best  = max(days, key=lambda d: getattr(d, "probability_score", 0) or 0)
        highs = [
            d for d in days
            if _sev_value(getattr(d, "severity_level", "Low")) in ("High", "Critical")
        ]
        story.append(Paragraph("Risk Summary", sec_s))
        offset = getattr(best, "forecast_day_offset", 0) or 0
        summary_rows = [
            ["Metric", "Value"],
            ["Highest risk day",     f"Day {offset + 1}"],
            ["Peak probability",     f"{(getattr(best, 'probability_score', 0) or 0):.0%}"],
            ["Peak severity",        _sev_value(getattr(best, "severity_level", "Unknown"))],
            ["Most likely disaster", getattr(best, "disaster_type", "Unknown") or "Unknown"],
            ["High / Critical days", str(len(highs))],
        ]
        t = Table(summary_rows, colWidths=["55%", "45%"])
        t.setStyle(_make_table_style())
        story.append(t)

    # ── Day-by-day table ──────────────────────────────────────────────────────
    story.append(Paragraph("Day-by-Day Forecast", sec_s))
    rows = [["Day", "Disaster Type", "Probability", "Severity", "Risk Score"]]
    for day in sorted(days, key=lambda d: getattr(d, "forecast_day_offset", 0) or 0):
        rows.append([
            str((getattr(day, "forecast_day_offset", 0) or 0) + 1),
            getattr(day, "disaster_type", "—") or "—",
            f"{(getattr(day, 'probability_score', 0) or 0):.0%}",
            _sev_value(getattr(day, "severity_level", "Unknown")),
            f"{(getattr(day, 'risk_score', 0) or 0):.1f}",
        ])
    t2 = Table(rows, colWidths=["10%", "30%", "18%", "22%", "20%"])
    t2.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  _DARK),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.white),
        ("FONTSIZE",      (0, 0), (-1, 0),  9),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("ALIGN",         (2, 0), (4, -1),  "CENTER"),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, _PALE]),
        ("BOX",           (0, 0), (-1, -1), 0.5, _LINE),
        ("INNERGRID",     (0, 0), (-1, -1), 0.5, _LINE),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
    ]))
    story.append(t2)

    # ── Footer disclaimer ─────────────────────────────────────────────────────
    story.append(Spacer(1, 14))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LINE))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "Injury and damage estimates are based on ~26% and ~33% of recorded events "
        "respectively. Forecast based on historical patterns and seasonal trends "
        "— not live weather data.",
        dis_s,
    ))
    story.append(Spacer(1, 2))
    story.append(Paragraph(_FOOTER_TEXT, dis_s))

    doc.build(story)
    return buf.getvalue()
